### ISSUE TITLE
Add first and last hadith number of every section

### ISSUE THREAD

**Issue by unkn4wn** [fawazahmed0/hadith-api#20]
Asselamu Aleykum,
An example can be found here: https://sunnah.com/tirmidhi

The Book on Purification 
firsthadith 1
lasthadith 148

The Book on Salat
firsthadith 149 
lasthadith 451
etc...

This makes the navigation more simple, because its possible to display the range of ahadith number in a section to the user

**Comment by GibreelAbdullah** [comment]
Sunnah.com has some issues, Eg- https://sunnah.com/tirmidhi
Check the starting and ending of last 3 chapters

![image](https://user-images.githubusercontent.com/10581984/195995886-3545cda9-3146-47a4-b3dd-9afa5a7f8602.png)

I have figured out why they have this issue, and will fix and provide more accurate data however first [this issue needs to be fixed](https://github.com/fawazahmed0/hadith-api/issues/23) since my code is dependent on this.

**Comment by GibreelAbdullah** [comment]
Assalamualaekum brother/sister @unkn4wn, didn't find any other way to connect with you.

Have you published your app hadith-pro to the app/play store?
I have created a website [HadithHub.com](www.hadithhub.com) which uses the data collected by brother Fawaz.

Would like to connect with you. Kindly message me on twitter [TheHadithHub](https://twitter.com/TheHadithHub)or drop me a mail - gibreel.khan@gmail.com

**Comment by GibreelAbdullah** [comment]
@fawazahmed0 I have created a script and generated a separate file which contains this data. Do let me know if I should raise a PR for the same?

https://github.com/GibreelAbdullah/hadith-api/blob/2/updates/sections/abudawud.json

The script can be found here -> https://github.com/GibreelAbdullah/hadith-api-updater/blob/master/03-Books/02-BookDetailsTemp.py

**Comment by fawazahmed0** [comment]
should be fixed now
