### ISSUE TITLE
Standardized references for Kutub al-Sittah

### ISSUE THREAD

**Issue by unkn4wn** [fawazahmed0/hadith-api#46]
Asselamu Aleykum,
There should be a standardized reference for ahadith. For now some references are adopted by sunnah.com while others are adopted by urdu sites, darussalam etc.. We should stick to one principle.

Example: 
Urdu sites and the official darussalam book is showing this hadith in "Sunan An-Nasai 208":
https://hamariweb.com/islam/hadith/sunan-an-nasai-208/
https://kalamullah.com/Books/Hadith/Sunan%20an-Nasai%20Vol.%201%20-%201-876.pdf

While Sunnah.com and this api shows the hadith "209" in "Sunan An-Nasai 208" and completely skips "208":
https://sunnah.com/nasai:208
https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions/eng-nasai/208.json

I can fix it, that's not the problem but I need to know which standard we are referring to. 
My suggestion would be lets use the reference given by darussalam and Hafidh Zubair Ali Zai because sunnah.com skips some Ahadith:
https://kalamullah.com/sahih-bukhari.html
https://kalamullah.com/sahih-muslim.html
https://kalamullah.com/sunan-an-nasai.html
https://kalamullah.com/jami-at-tirmidhi.html
https://kalamullah.com/sunan-abu-dawood.html
https://kalamullah.com/ibn-majah.html

**Comment by fawazahmed0** [comment]
sunnah api uses arabic reference numbering, even my api (except sahih muslim) uses arabic reference number. The darussalam book seems to have mistake.

For example, hadith no 875
[sunnah.com](https://sunnah.com/nasai:875)
[hadith-api](https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions/eng-nasai/875.json)
[islamweb](https://islamweb.net/ar/library/index.php?page=bookcontents&flag=1&bk_no=3&ID=865#:~:text=%D8%A7%D9%84%D8%B3%D8%A7%D8%A8%D9%82-,875,-%D8%A3%D8%AE%D8%A8%D8%B1%D9%86%D8%A7%20%D9%85%D8%AD%D9%85%D8%AF%20%D8%A8%D9%86)
[Darussalam](https://kalamullah.com/Books/Hadith/Sunan%20an-Nasai%20Vol.%201%20-%201-876.pdf#page=517) (mistake)


For sahih muslim, there are two [reference numbering systems](https://hadithanswers.com/question-regarding-hadith-numbers-in-sahih-muslim/#:~:text=There%20are%20two,edition%20is%3A%207479.) .
I chose a different numbering system(i.e numbering repeats), because the arabic numbering(i.e numbering excluding repeats) was creating few issues for me during development.

**Comment by unkn4wn** [comment]
Jazakhallahu Khayr, you are right!
So we can use sunnah.com and islamweb (arabic reference) as reference except in Sahih Muslim.

How do you plan to deal with [these ](https://sunnah.com/nasai:4938) ones ?

Should it be like this:
```
                                "hadithnumber": 4938,
				"arabicnumber": 4938,
				"grades": [],
				"reference": {
					"book": 46,
					"hadith": 69
				}
			},
			{
				"hadithnumber": 4939,
				"arabicnumber": 4939,
				"grades": [],
				"reference": {
					"book": 0,
					"hadith": 0
				}
			},
```

or should we write in both of them:
```
"book": 46,
"hadith": 69
```

**Comment by fawazahmed0** [comment]
for `"book": , "hadith": ` field i have used data from [sunnah.com](https://sunnah.com/nasai:4938#:~:text=%C2%A0%3A-,Book%2046%2C%20Hadith%2069,-English%20translation), so I guess using `"book":46, "hadith":69` in both should be the right thing do to.

**Comment by unkn4wn** [comment]
> for `"book": , "hadith": ` field i have used data from [sunnah.com](https://sunnah.com/nasai:4938#:~:text=%C2%A0%3A-,Book%2046%2C%20Hadith%2069,-English%20translation), so I guess using `"book":46, "hadith":69` in both should be the right thing do to.

What about the text? Should all the text be written in 4938 and 4939 is empty or more like this:

4938:
I heard 'Urwah bin Az-Zubair say: "Aishah used to narrate that he Prophet of Allah said: The hand (of the thief) should not be cut off except for a shield or its equivalent in value. And he said that 'Urwah said: A shield is (worth) four Dirhams.

4939:
And he (the narrator) said: I heard sulaiman bin Yasar say that he heard 'Amrah say: I heard 'Aishah narrate that she heard the Messenger of Allah say: The hand (of the thief) should not be cut off except for four Dinars or more.

**Comment by fawazahmed0** [comment]
> 4938:
> I heard 'Urwah bin Az-Zubair say: "Aishah used to narrate that he Prophet of Allah said: The hand (of the thief) should not be cut off except for a shield or its equivalent in value. And he said that 'Urwah said: A shield is (worth) four Dirhams.
> 
> 4939:
> And he (the narrator) said: I heard sulaiman bin Yasar say that he heard 'Amrah say: I heard 'Aishah narrate that she heard the Messenger of Allah say: The hand (of the thief) should not be cut off except for four Dinars or more.

yes, same as above, because [shamela](https://shamela.ws/book/829/7169#p1) also follows same pattern.
